# Default values for botivater-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cloudflared:
  token:

discord-bot:
  settings:
    general:
      logLevel: debug
      apiToken:
    database:
      url:
    discord:
      applicationId:
      botToken:
    auth0:
      domain:
      clientId:
      audience:
